config/routes.rb
DeviseUsers::Engine.routes.draw do

  root to: 'devise_users#active_users'

  resources :devise_users, path: :users, as: :users do
    collection do
      get 'search'
    end
  end

end

app/controllers/devise_users/application_controller.rb
module DeviseUsers
  class ApplicationController < ActionController::Base
    include Devise::Controllers::Helpers
    include Devise::Controllers::SignInOut
    before_action :authenticate_devise_resource, :total_user_number

  private
    def authenticate_devise_resource
      unless signed_in?(devise_resource_name)
        redirect_to new_session_path(devise_resource_name), notice: t('devise_users.authentication_required')
        return
      end

      unless devise_resource_object.respond_to?(:devise_user_manager?) and devise_resource_object.devise_user_manager?
        redirect_to DeviseUsers.unauthorisation_url, notice: t('devise_users.authorisation_required')
        return
      end
    end

    def devise_resource_class
      devise_resource_object.class
    end

    def total_user_number
      @total_user_number = devise_resource_class.count
    end
    helper_method :total_user_number

    def devise_resource_object
      @devise_resource_object = self.send "current_#{devise_resource_name}".to_sym
    end
    helper_method :devise_resource_object

    def devise_resource_name
      DeviseUsers.devise_resource_name.to_sym
    end
    helper_method :devise_resource_name
  end
end

app/controllers/devise_users/devise_users_controller.rb
require_dependency "devise_users/application_controller"

module DeviseUsers
  class DeviseUsersController < ApplicationController

    def index
      @menu_item = :user_list
      @users_count = total_user_number
      @users = all_users
    end

    def new
      @user = devise_resource_class.new
    end

    def create
      @user = devise_resource_class.new user_params
      unless @user.save
        render :new
      else
        redirect_to @user
      end
    end

    def show
      @user = devise_resource_class.find params[:id]
    end

    def edit
      @user = devise_resource_class.find params[:id]
    end

    def update
      @user = devise_resource_class.find params[:id]
      unless @user.update_attributes user_params
        render :edit
      else
        redirect_to @user
      end
    end

    def destroy
      @user = devise_resource_class.find params[:id]
      @user.destroy
      redirect_to users_url, notice: 'user'
    end

    def search
      search_query = devise_resource_class.where("email LIKE ?", "%#{params[:q]}%")
      @users_count = search_query.count
      @users = search_query.order('created_at desc').page(params[:page]).per 1
      @searching = true
      render :index
    end

    def active_users
      @menu_item = :active_users
      @recent_users = query_active_users
    end

  private
    def query_active_users
      devise_resource_class.limit(20).order('current_sign_in_at desc, last_sign_in_at desc')
    end

    def all_users
      devise_resource_class.order('created_at desc').page params[:page]
    end

    def user_params
      params.require(:user).permit :email, :password
    end

  end
end

app/helpers/devise_users/application_helper.rb
module DeviseUsers
  module ApplicationHelper
  end
end

app/views/devise_users/devise_users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <div class='box-body'>
    <%= f.error_notification %>

    <%= f.input :email, placeholder: 'Enter email' %>

    <%= f.input :password, placeholder: 'Password' %>
  </div>

  <div class="box-footer"><%= f.button :submit %></div>
<% end %>

app/views/devise_users/devise_users/active_users.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body data-table-wrapper">
        <table class="table table-bordered table-hover data-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>EMail</th>
              <th>Last Signed in At</th>
              <th>Sign in Count</th>
              <th>Created At</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @recent_users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td>
                <%= user.email %>
              </td>
              <td>
                <% if user.current_sign_in_at.present? or user.last_sign_in_at.present? %>
                <%= (user.current_sign_in_at || user.last_sign_in_at).in_time_zone %>
                <% end %>
              </td>
              <td>
                <%= user.sign_in_count %>
              </td>
              <td><%= user.created_at.in_time_zone %></td>
              <td class="text-center user-action">
                <%= link_to user_path(user) do %>
                <i class="fa fa-hand-o-right"></i>
                <% end %>
                <%= link_to edit_user_path(user) do %>
                <i class="fa fa-edit"></i>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="row">
          <div class="col-xs-6">
            <div class="data-table-info">Showing <%= @recent_users.count %> active users out of total <%= total_user_number %></div>
          </div>
          <div class="col-xs-6">
          </div>
        </div>
      </div>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
</div>

<% content_for :header do %>
Active Users <small>who signed in recently</small>
<% end %>

app/views/devise_users/devise_users/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <%= render 'form' %>
    </div>
  </div>
</div>

<% content_for :header do %>
  Edit User
<% end %>

app/views/devise_users/devise_users/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body data-table-wrapper">
        <table class="table table-bordered table-hover data-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>EMail</th>
              <th>Created At</th>
              <th>Updated At</th>
              <th>Last Signed in At</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td>
                <%= user.email %>
              </td>
              <td><%= user.created_at.in_time_zone %></td>
              <td><%= user.updated_at.in_time_zone if user.updated_at.present? %></td>
              <td><%= user.last_sign_in_at.in_time_zone if user.last_sign_in_at.present? %></td>
              <td class="text-center user-action">
                <%= link_to user_path(user) do %>
                <i class="fa fa-hand-o-right"></i>
                <% end %>
                <%= link_to edit_user_path(user) do %>
                <i class="fa fa-edit"></i>
                <% end %>
                <%= link_to user_path(user), method: :delete, data: { confirm: 'Are you sure to delete this user?' } do %>
                <i class="fa fa-trash"></i>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="row">
          <div class="col-xs-6">
            <div class="data-table-info">Showing <%= @users.count %> of total <%= @users_count %></div>
          </div>
          <div class="col-xs-6">
            <%= paginate @users %>
          </div>
        </div>
      </div>
    </div>
    <!-- /.box-body -->
  </div>
  <!-- /.box -->
</div>

<% content_for :header do %>
  <% if @searching %>
  Search Users <small>users match your search criterias <strong>'<%=params[:q]%>'</strong></small>
  <% else %>
  User List <small>all devise users</small>
  <% end %>
<% end %>

app/views/devise_users/devise_users/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <%= render 'form' %>
    </div>
  </div>
</div>

<% content_for :header do %>
  Create new User
<% end %>

app/views/devise_users/devise_users/search.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-body data-table-wrapper">
        Search users list
      </div>
    </div>
  </div>
</div>

<% content_for :header do %>
Search Users <small>users match your search criterias</small>
<% end %>

app/views/devise_users/devise_users/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="box">
      <div class="box-header">
        <h3 class="box-title"><%= @user.email %></h3>
      </div><!-- /.box-header -->
      <div class="box-body no-padding">
        <table class="table table-condensed show-table">
          <tbody>
            <tr>
              <td class="view-label">Sign in Count</td>
              <td><%= @user.sign_in_count %></td>
            </tr>
            <tr>
              <td class="view-label">Current Sign in At</td>
              <td><%= @user.current_sign_in_at.in_time_zone if @user.current_sign_in_at.present? %></td>
            </tr>
            <tr>
              <td class="view-label">Current Sign in IP</td>
              <td><%= @user.current_sign_in_ip %></td>
            </tr>
            <tr>
              <td class="view-label">Last Sign in At</td>
              <td><%= @user.last_sign_in_at.in_time_zone if @user.last_sign_in_at.present? %></td>
            </tr>
            <tr>
              <td class="view-label">Last Sign in IP</td>
              <td><%= @user.last_sign_in_ip %></td>
            </tr>
            <tr>
              <td class="view-label">Created At</td>
              <td><%= @user.created_at.in_time_zone %></td>
            </tr>
            <tr>
              <td class="view-label">Updated At</td>
              <td><%= @user.updated_at.in_time_zone if @user.updated_at.present? %></td>
            </tr>
          </tbody>
        </table>
      </div><!-- /.box-body -->
    </div>
  </div>
</div>

<% content_for :header do %>
  User Details
<% end %>

app/views/devise_users/shared/_side_bar.html.erb
<section class="sidebar">
  <!-- search form -->
  <form action="<%= search_users_path %>" method="get" class="sidebar-form">
    <div class="input-group">
      <input type="text" name="q" class="form-control" placeholder="Search Users..."/>
      <span class="input-group-btn">
        <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
      </span>
    </div>
  </form>
  <!-- /.search form -->
  <!-- sidebar menu -->
  <ul class="sidebar-menu">
    <li class="<%= 'active' if @menu_item == :active_users %>">
      <%= link_to root_path do %>
        <i class="fa fa-clock-o"></i> <span>Active Users</span>
      <% end %>
    </li>
    <li class="<%= 'active' if @menu_item == :user_list %>">
      <%= link_to users_path do %>
        <i class="fa fa-users"></i> <span>User List</span>
        <small class="badge pull-right bg-green"><%= total_user_number %></small>
      <% end %>
    </li>
  </ul>
</section><!-- /.sidebar -->

app/views/devise_users/shared/_user_bar.html.erb
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
  <i class="glyphicon glyphicon-user"></i>
  <span><%= devise_resource_object.email %> <i class="caret"></i></span>
</a>
<ul class="dropdown-menu">
  <!-- User image -->
  <li class="user-header bg-light-blue">
    <p>
      <span class="color-white"><%= devise_resource_object.email %></span>
      <small>Last login: <%= devise_resource_object.last_sign_in_at.in_time_zone if devise_resource_object.last_sign_in_at.present? %></small>
    </p>
  </li>
  <!-- Menu Footer-->
  <li class="user-footer">
    <div class="pull-left"></div>
    <div class="pull-right">
      <%= link_to 'Sign Out', destroy_session_path(devise_resource_name), class: 'btn btn-default btn-flat', method: :delete %>
    </div>
  </li>
</ul>

app/views/layouts/devise_users/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Devise Users</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    "devise_users/ionicons.min", media: "all" %>
    <%= stylesheet_link_tag    "devise_users/AdminLTE", media: "all" %>
    <%= stylesheet_link_tag    "devise_users/sweet-alert", media: "all" %>
    <%= stylesheet_link_tag    "devise_users/application", media: "all" %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="skin-blue">
    <header class="header">
      <a href="<%= root_path %>" class="logo">
        <i class="fa fa-users fa-reverse"></i> Devise Users
      </a>
      <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <div class="navbar-right">
          <ul class="nav navbar-nav">
            <li class="dropdown user user-menu">
              <%= render '/devise_users/shared/user_bar' %>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <div class="wrapper row-offcanvas row-offcanvas-left">
      <aside class="left-side sidebar-offcanvas">
        <%= render '/devise_users/shared/side_bar' %>
        <div style="text-align: center;margin-top: 30px;">
          <%= link_to 'Create User', new_user_path, class: 'btn btn-primary' %>
        </div>
      </aside>

      <aside class="right-side">
        <section class="content-header">
          <h1><%= yield :header %></h1>
        </section>

        <!-- Main content -->
        <section class="content">
        <%= yield %>
        </section><!-- /.content -->
      </aside><!-- /.right-side -->
    </div><!-- ./wrapper -->

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <%= javascript_include_tag "devise_users/AdminLTE" %>
    <%= javascript_include_tag "devise_users/sweet-alert.min" %>
    <%= javascript_include_tag "devise_users/application" %>
  </body>
</html>